const mongoose = require('mongoose');
const IPO = require('./models/IPO');
require('dotenv').config();

async function addMoreIPOs() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    const additionalIPOs = [
      {
        company: 'Infosys BPM Ltd',
        symbol: 'INFYBPM',
        sector: 'IT Services',
        status: 'open',
        description: 'Leading business process management company providing digital transformation services and AI-powered automation solutions.',
        priceBand: { min: 1350, max: 1375 },
        issuePrice: 1362,
        lotSize: 100,
        minInvestment: 136200,
        openDate: new Date('2024-02-03'),
        closeDate: new Date('2024-02-07'),
        issueSize: '₹13,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 95000000,
        sharesOffered: 95300000,
        peRatio: 28.5,
        eps: 47.79,
        marketCap: '₹26,000 Cr',
        qibSubscription: 3.2,
        niiSubscription: 4.8,
        retailSubscription: 8.5,
        totalSubscription: 5.5,
        promoterHolding: '55%',
        riskLevel: 'low',
        expectedReturn: '12-18%',
        logo: 'https://example.com/logos/infosys-bpm.png',
        views: 18900,
        watchlistCount: 1234
      },
      {
        company: 'Bajaj Finance Digital',
        symbol: 'BAJFIN',
        sector: 'Finance',
        status: 'open',
        description: 'Digital lending platform offering personal loans, business loans, and financial services with AI-powered credit assessment.',
        priceBand: { min: 1865, max: 1890 },
        issuePrice: 1877,
        lotSize: 80,
        minInvestment: 150160,
        openDate: new Date('2024-02-04'),
        closeDate: new Date('2024-02-08'),
        issueSize: '₹9,500 Crore',
        issueType: 'Fresh Issue',
        totalShares: 50000000,
        sharesOffered: 50600000,
        peRatio: 22.5,
        eps: 83.42,
        marketCap: '₹18,900 Cr',
        qibSubscription: 4.5,
        niiSubscription: 6.2,
        retailSubscription: 11.8,
        totalSubscription: 7.5,
        promoterHolding: '58%',
        riskLevel: 'medium',
        expectedReturn: '15-20%',
        logo: 'https://example.com/logos/bajaj-finance.png',
        views: 15600,
        watchlistCount: 987
      },
      {
        company: 'Larsen & Toubro Infotech',
        symbol: 'LTIINFOTECH',
        sector: 'Technology',
        status: 'open',
        description: 'IT services and consulting arm of L&T group, specializing in digital transformation, cloud services, and enterprise solutions.',
        priceBand: { min: 875, max: 895 },
        issuePrice: 885,
        lotSize: 150,
        minInvestment: 132750,
        openDate: new Date('2024-02-05'),
        closeDate: new Date('2024-02-09'),
        issueSize: '₹7,500 Crore',
        issueType: 'Fresh Issue',
        totalShares: 85000000,
        sharesOffered: 84700000,
        peRatio: 32.5,
        eps: 27.23,
        marketCap: '₹17,000 Cr',
        qibSubscription: 2.8,
        niiSubscription: 4.2,
        retailSubscription: 7.8,
        totalSubscription: 4.9,
        promoterHolding: '62%',
        riskLevel: 'medium',
        expectedReturn: '18-22%',
        logo: 'https://example.com/logos/lnt-infotech.png',
        views: 13400,
        watchlistCount: 876
      },
      {
        company: 'Dr. Reddy\'s Laboratories',
        symbol: 'DRREDDY',
        sector: 'Healthcare',
        status: 'upcoming',
        description: 'Global pharmaceutical company with presence in over 60 countries, specializing in generic medicines and APIs.',
        priceBand: { min: 2450, max: 2480 },
        lotSize: 60,
        minInvestment: 148800,
        openDate: new Date('2024-02-12'),
        closeDate: new Date('2024-02-16'),
        issueSize: '₹6,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 24000000,
        sharesOffered: 24200000,
        peRatio: 18.5,
        eps: 134.05,
        marketCap: '₹12,000 Cr',
        promoterHolding: '52%',
        riskLevel: 'low',
        expectedReturn: '10-15%',
        logo: 'https://example.com/logos/dr-reddy.png',
        views: 11200,
        watchlistCount: 654
      },
      {
        company: 'Sun Pharmaceutical Industries',
        symbol: 'SUNPHARMA',
        sector: 'Healthcare',
        status: 'upcoming',
        description: 'Leading Indian pharmaceutical company with global presence in specialty and generic medicines.',
        priceBand: { min: 680, max: 695 },
        lotSize: 200,
        minInvestment: 139000,
        openDate: new Date('2024-02-15'),
        closeDate: new Date('2024-02-19'),
        issueSize: '₹8,500 Crore',
        issueType: 'Fresh Issue',
        totalShares: 125000000,
        sharesOffered: 122250000,
        peRatio: 25.5,
        eps: 26.67,
        marketCap: '₹17,000 Cr',
        promoterHolding: '70%',
        riskLevel: 'medium',
        expectedReturn: '12-17%',
        logo: 'https://example.com/logos/sun-pharma.png',
        views: 14500,
        watchlistCount: 789
      },
      {
        company: 'Havells India Ltd',
        symbol: 'HAVELLS',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'Leading electrical equipment manufacturer with presence in power equipment, cables, and consumer electricals.',
        priceBand: { min: 1550, max: 1580 },
        lotSize: 100,
        minInvestment: 158000,
        openDate: new Date('2024-02-18'),
        closeDate: new Date('2024-02-22'),
        issueSize: '₹4,500 Crore',
        issueType: 'Offer for Sale',
        totalShares: 28000000,
        sharesOffered: 28400000,
        peRatio: 35.5,
        eps: 44.51,
        marketCap: '₹11,200 Cr',
        promoterHolding: '61%',
        riskLevel: 'low',
        expectedReturn: '8-12%',
        logo: 'https://example.com/logos/havells.png',
        views: 9800,
        watchlistCount: 543
      },
      {
        company: 'Asian Paints Ltd',
        symbol: 'ASIANPAINTS',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'India\'s largest paint company with extensive distribution network and presence in decorative and industrial paints.',
        priceBand: { min: 3450, max: 3500 },
        lotSize: 50,
        minInvestment: 175000,
        openDate: new Date('2024-02-20'),
        closeDate: new Date('2024-02-24'),
        issueSize: '₹3,500 Crore',
        issueType: 'Offer for Sale',
        totalShares: 10000000,
        sharesOffered: 10000000,
        peRatio: 42.5,
        eps: 81.18,
        marketCap: '₹14,000 Cr',
        promoterHolding: '68%',
        riskLevel: 'low',
        expectedReturn: '10-15%',
        logo: 'https://example.com/logos/asian-paints.png',
        views: 16700,
        watchlistCount: 912
      },
      {
        company: 'Maruti Suzuki India Ltd',
        symbol: 'MARUTI',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'India\'s largest passenger car manufacturer with over 50% market share in the domestic passenger car market.',
        priceBand: { min: 950, max: 965 },
        lotSize: 150,
        minInvestment: 144750,
        openDate: new Date('2024-02-22'),
        closeDate: new Date('2024-02-26'),
        issueSize: '₹12,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 125000000,
        sharesOffered: 124250000,
        peRatio: 28.5,
        eps: 33.86,
        marketCap: '₹25,000 Cr',
        promoterHolding: '56%',
        riskLevel: 'medium',
        expectedReturn: '12-18%',
        logo: 'https://example.com/logos/maruti-suzuki.png',
        views: 23400,
        watchlistCount: 1567
      },
      {
        company: 'Titan Company Ltd',
        symbol: 'TITAN',
        sector: 'Retail',
        status: 'upcoming',
        description: 'Leading lifestyle company with presence in watches, jewelry, eyewear, and accessories across multiple brands.',
        priceBand: { min: 1250, max: 1280 },
        lotSize: 120,
        minInvestment: 153600,
        openDate: new Date('2024-02-25'),
        closeDate: new Date('2024-03-01'),
        issueSize: '₹6,500 Crore',
        issueType: 'Fresh Issue',
        totalShares: 50000000,
        sharesOffered: 50800000,
        peRatio: 38.5,
        eps: 32.47,
        marketCap: '₹16,000 Cr',
        promoterHolding: '53%',
        riskLevel: 'medium',
        expectedReturn: '15-20%',
        logo: 'https://example.com/logos/titan.png',
        views: 18900,
        watchlistCount: 1234
      },
      {
        company: 'UltraTech Cement Ltd',
        symbol: 'ULTRATECHCEM',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'India\'s largest cement manufacturer with integrated operations and presence in ready-mix concrete and construction chemicals.',
        priceBand: { min: 785, max: 800 },
        lotSize: 180,
        minInvestment: 144000,
        openDate: new Date('2024-02-27'),
        closeDate: new Date('2024-03-03'),
        issueSize: '₹9,000 Crore',
        issueType: 'Fresh Issue',
        totalShares: 112500000,
        sharesOffered: 112500000,
        peRatio: 32.5,
        eps: 24.62,
        marketCap: '₹18,000 Cr',
        promoterHolding: '60%',
        riskLevel: 'medium',
        expectedReturn: '12-17%',
        logo: 'https://example.com/logos/ultratech-cement.png',
        views: 15600,
        watchlistCount: 987
      },
      {
        company: 'Godrej Consumer Products Ltd',
        symbol: 'GODREJCP',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'Leading FMCG company with presence in household insecticides, air fresheners, and personal care products.',
        priceBand: { min: 650, max: 665 },
        lotSize: 220,
        minInvestment: 143000,
        openDate: new Date('2024-03-01'),
        closeDate: new Date('2024-03-05'),
        issueSize: '₹5,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 75000000,
        sharesOffered: 75250000,
        peRatio: 45.5,
        eps: 14.29,
        marketCap: '₹15,000 Cr',
        promoterHolding: '64%',
        riskLevel: 'low',
        expectedReturn: '10-15%',
        logo: 'https://example.com/logos/godrej-cp.png',
        views: 13400,
        watchlistCount: 876
      },
      {
        company: 'Britannia Industries Ltd',
        symbol: 'BRITANNIA',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'One of India\'s largest food companies with leading market share in bakery products and presence in dairy and snacks.',
        priceBand: { min: 3850, max: 3900 },
        lotSize: 40,
        minInvestment: 156000,
        openDate: new Date('2024-03-04'),
        closeDate: new Date('2024-03-08'),
        issueSize: '₹4,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 10000000,
        sharesOffered: 10300000,
        peRatio: 52.5,
        eps: 73.33,
        marketCap: '₹20,000 Cr',
        promoterHolding: '51%',
        riskLevel: 'low',
        expectedReturn: '8-12%',
        logo: 'https://example.com/logos/britannia.png',
        views: 17800,
        watchlistCount: 1098
      },
      {
        company: 'Jubilant FoodWorks Ltd',
        symbol: 'JUBLFOOD',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'Leading food services company with presence in Domino\'s Pizza and other quick service restaurant chains.',
        priceBand: { min: 1450, max: 1480 },
        lotSize: 130,
        minInvestment: 192400,
        openDate: new Date('2024-03-06'),
        closeDate: new Date('2024-03-10'),
        issueSize: '₹3,500 Crore',
        issueType: 'Offer for Sale',
        totalShares: 24000000,
        sharesOffered: 23650000,
        peRatio: 65.5,
        eps: 22.14,
        marketCap: '₹14,000 Cr',
        promoterHolding: '75%',
        riskLevel: 'medium',
        expectedReturn: '15-20%',
        logo: 'https://example.com/logos/jubilant.png',
        views: 19800,
        watchlistCount: 1345
      },
      {
        company: 'Avenue Supermarts Ltd',
        symbol: 'AVENUE',
        sector: 'Retail',
        status: 'upcoming',
        description: 'Leading supermarket chain in India with over 300 stores across major cities and focus on food and grocery retail.',
        priceBand: { min: 485, max: 495 },
        lotSize: 300,
        minInvestment: 148500,
        openDate: new Date('2024-03-08'),
        closeDate: new Date('2024-03-12'),
        issueSize: '₹5,000 Crore',
        issueType: 'Fresh Issue',
        totalShares: 100000000,
        sharesOffered: 101000000,
        peRatio: 55.5,
        eps: 8.74,
        marketCap: '₹10,000 Cr',
        promoterHolding: '62%',
        riskLevel: 'high',
        expectedReturn: '18-25%',
        logo: 'https://example.com/logos/avenue.png',
        views: 21200,
        watchlistCount: 1567
      },
      {
        company: 'Dabur India Ltd',
        symbol: 'DABUR',
        sector: 'Healthcare',
        status: 'upcoming',
        description: 'One of India\'s leading Ayurvedic and natural healthcare companies with presence in pharmaceuticals and consumer products.',
        priceBand: { min: 575, max: 585 },
        lotSize: 250,
        minInvestment: 146250,
        openDate: new Date('2024-03-10'),
        closeDate: new Date('2024-03-14'),
        issueSize: '₹4,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 68000000,
        sharesOffered: 68700000,
        peRatio: 48.5,
        eps: 11.86,
        marketCap: '₹12,000 Cr',
        promoterHolding: '67%',
        riskLevel: 'low',
        expectedReturn: '10-15%',
        logo: 'https://example.com/logos/dabur.png',
        views: 16700,
        watchlistCount: 987
      },
      {
        company: 'ICICI Lombard General Insurance',
        symbol: 'ICICIGI',
        sector: 'Finance',
        status: 'upcoming',
        description: 'Leading private sector general insurance company offering health, motor, travel, and other insurance products.',
        priceBand: { min: 665, max: 675 },
        lotSize: 220,
        minInvestment: 146300,
        openDate: new Date('2024-03-12'),
        closeDate: new Date('2024-03-16'),
        issueSize: '₹7,000 Crore',
        issueType: 'Fresh Issue',
        totalShares: 105000000,
        sharesOffered: 104000000,
        peRatio: 25.5,
        eps: 26.08,
        marketCap: '₹14,000 Cr',
        promoterHolding: '48%',
        riskLevel: 'medium',
        expectedReturn: '12-18%',
        logo: 'https://example.com/logos/icici-lombard.png',
        views: 18900,
        watchlistCount: 1234
      },
      {
        company: 'Hindustan Unilever Ltd',
        symbol: 'HUL',
        sector: 'Manufacturing',
        status: 'upcoming',
        description: 'India\'s largest FMCG company with presence in soaps, detergents, personal care, and food products.',
        priceBand: { min: 2350, max: 2400 },
        lotSize: 80,
        minInvestment: 192000,
        openDate: new Date('2024-03-15'),
        closeDate: new Date('2024-03-19'),
        issueSize: '₹6,000 Crore',
        issueType: 'Offer for Sale',
        totalShares: 25000000,
        sharesOffered: 25500000,
        peRatio: 58.5,
        eps: 40.17,
        marketCap: '₹24,000 Cr',
        promoterHolding: '62%',
        riskLevel: 'low',
        expectedReturn: '8-12%',
        logo: 'https://example.com/logos/hul.png',
        views: 24500,
        watchlistCount: 1678
      }
    ];

    const createdIPOs = await IPO.insertMany(additionalIPOs);
    console.log(`✅ Added ${createdIPOs.length} additional IPOs`);

    // Update statistics
    const totalIPOs = await IPO.countDocuments();
    const openIPOs = await IPO.countDocuments({ status: 'open' });
    const upcomingIPOs = await IPO.countDocuments({ status: 'upcoming' });
    const listedIPOs = await IPO.countDocuments({ status: 'listed' });

    console.log('📊 Updated IPO Statistics:');
    console.log(`   Total IPOs: ${totalIPOs}`);
    console.log(`   Open IPOs: ${openIPOs}`);
    console.log(`   Upcoming IPOs: ${upcomingIPOs}`);
    console.log(`   Listed IPOs: ${listedIPOs}`);

    // Show sample of newly added IPOs
    console.log('\n📋 Newly Added IPOs:');
    createdIPOs.slice(0, 5).forEach((ipo, index) => {
      console.log(`${index + 1}. ${ipo.company} (${ipo.symbol}) - ${ipo.status}`);
    });

    mongoose.connection.close();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error adding more IPOs:', error);
    process.exit(1);
  }
}

addMoreIPOs();
